spring.application.name=afam-backend

# Configurazione della connessione al DB di Docker
spring.datasource.url=jdbc:mysql://localhost:3307/afam_db
spring.datasource.username=root
# Se hai usato il mio file docker-compose, la password è 'root' (o 'vostra_password')
spring.datasource.password=root

# Logica di auto-creazione delle tabelle partendo dalle classi Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Config mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=claudio.luparello.2005@gmail.com
spring.mail.password=oyytbtrjxunugeqj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
